### ISSUE TITLE
Doesn't work latest OOS in OP3

### ISSUE THREAD

**Issue by arvind-gr** [vemacs/HideVoLTEIcon#2]
I'm using OxygenOS Community build 3.5.3, and am so desperate to hide VoLTE icon since it uselessly takes many status bar space. Your module doesn't work in that. How can I help you further on this?

**Comment by Nekotora** [comment]
The same to me! 
VOLTE icon is too large that makes me unbearable. This module dosen't work on H2OS 2.5.2 too.
Expecting you to fix it. Thanks a lot!

**Comment by arvind-gr** [comment]
Not needed
